Works in Docker on MacOS
The runtime DAG fails (which is just fine, because it's working on a mock
Broken DAG: [/opt/airflow/dags/glacier_staging_to_sync.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/shutil.py", line 431, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dev/tmp/Projects/airflow/glacier_staging_to_sync/save-W1FPL2251.bag.zip'